name: Coverage

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Calculate Code Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: npm install
      run: npm i
    - name: Run Code Coverage
      run: npm run coverage
    - name: Create Code Coverage Report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        fail_ci_if_error: true
